### ISSUE TITLE
Store jobs metadata on sqlite

### ISSUE THREAD

**Issue by ndelvalle** [Huemul/subilo#61]
It would be nice to store all jobs metadata on a `sqlite` file instead of having a `metadata.json`

**Comment by gillchristian** [comment]
Currently the agent's api is driven by a file system. We read subilorc & the logs and meta files as a way to power the API.

This is very handy since the logs are basically the source of truth but is also impractical to write APIs based on the file system (eg. read all files in a directory to show list of jobs) and not very efficient either (specially if Subilo agent runs on a low resource machine).

Running a local embedded database (like SQLite) could solve some of these problems.

Some pros:

- more portable (ie. if user wants to move the state of an agent to another machine they just have to copy the sqlite file)
- easier to write APIs against it
- easier to extend and maintain data integrity
- more disk usage efficient than having metadata in JSON files (I guess :smirk:)
- some problems from the file system API are much easier to solve (eg. jobs ids)
